/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


import java.util.List;

// import javax.persistence.EntityManager;
// import javax.persistence.EntityManagerFactory;
// import javax.persistence.Persistence;
// import javax.persistence.Query;

/**
 *
 * @author scott
 */
public class Read extends javax.swing.JFrame {

    List<BankAccount> bankAccounts;
    List<Transaction> transactions;
    // Main prac2 = new Main();
    DBTransactions dbTransactions = new DBTransactions();

   

    /**
     * Creates new form Read
     */
    public Read() {
        initComponents();
        bankAccounts = dbTransactions.readBankAccounts();
        bankAccountList.setListData(bankAccounts.toArray(new BankAccount[0]));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        deleteNavbarButton = new javax.swing.JButton();
        readNavbarButton = new javax.swing.JButton();
        storeNavbarButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        transactionDetailsLabel2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        accountNumberInput = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        bankAccountList = new javax.swing.JList<>();
        jPanel3 = new javax.swing.JPanel();
        transactionDetailsLabel = new javax.swing.JLabel();
        transactionIdLabel = new javax.swing.JLabel();
        transactionIdValue = new javax.swing.JLabel();
        transactionDateLabel = new javax.swing.JLabel();
        transactionDateValue = new javax.swing.JLabel();
        transactionAmountLabel = new javax.swing.JLabel();
        transactionAmountValue = new javax.swing.JLabel();
        senderAccNumLabel = new javax.swing.JLabel();
        senderAccNumValue = new javax.swing.JLabel();
        receiverAccNumLabel = new javax.swing.JLabel();
        receiverAccNumValue = new javax.swing.JLabel();
        transactionTypeLabel = new javax.swing.JLabel();
        transactionTypeValue = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        transactionDetailsLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        accountNumberValue = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        accountHolderValue = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        transactionList = new javax.swing.JList<>();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1100, 800));

        deleteNavbarButton.setText("Delete");
        deleteNavbarButton.setActionCommand("Delete Bank Account");
        deleteNavbarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteNavbarButtonMouseClicked(evt);
            }
        });

        readNavbarButton.setText("Read");
        readNavbarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                readNavbarButtonMouseClicked(evt);
            }
        });

        storeNavbarButton.setText("Store");
        storeNavbarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                storeNavbarButtonMouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        transactionDetailsLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        transactionDetailsLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        transactionDetailsLabel2.setText("Search Bank Accounts");
        transactionDetailsLabel2.setToolTipText("");

        jLabel2.setText("Bank Account Number");

        accountNumberInput.setText("Enter account number");
        accountNumberInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                accountNumberInputFocusLost(evt);
            }
        });
        accountNumberInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountNumberInputMouseClicked(evt);
            }
        });

        searchButton.setText("Search");
        searchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchButtonMouseClicked(evt);
            }
        });

        bankAccountList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                bankAccountListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(bankAccountList);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(transactionDetailsLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(accountNumberInput, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(transactionDetailsLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(accountNumberInput))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        transactionDetailsLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        transactionDetailsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        transactionDetailsLabel.setText("Transaction Details");
        transactionDetailsLabel.setToolTipText("");

        transactionIdLabel.setText("Transaction ID");

        transactionIdValue.setText("Select Transaction");
        transactionIdValue.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        transactionDateLabel.setText("Transaction Date");

        transactionDateValue.setText("Select Transaction");
        transactionDateValue.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        transactionAmountLabel.setText("Transaction Amount");

        transactionAmountValue.setText("Select Transaction");
        transactionAmountValue.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        senderAccNumLabel.setText("Transaction Sender Account Number");

        senderAccNumValue.setText("Select Transaction");
        senderAccNumValue.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        receiverAccNumLabel.setText("Transaction Receiver Account Number");

        receiverAccNumValue.setText("Select Transaction");
        receiverAccNumValue.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        transactionTypeLabel.setText("Transaction Type");

        transactionTypeValue.setText("Select Transaction");
        transactionTypeValue.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(transactionIdValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(transactionTypeLabel)
                            .addComponent(receiverAccNumLabel)
                            .addComponent(senderAccNumLabel)
                            .addComponent(transactionAmountLabel)
                            .addComponent(transactionDateLabel)
                            .addComponent(transactionIdLabel))
                        .addGap(0, 135, Short.MAX_VALUE))
                    .addComponent(transactionDateValue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(transactionAmountValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(senderAccNumValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(receiverAccNumValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(transactionTypeValue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(transactionDetailsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(transactionDetailsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(transactionIdLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(transactionIdValue, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(transactionDateLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(transactionDateValue, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(transactionAmountLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(transactionAmountValue, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(senderAccNumLabel)
                .addGap(5, 5, 5)
                .addComponent(senderAccNumValue, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(receiverAccNumLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(receiverAccNumValue, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(transactionTypeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(transactionTypeValue, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(317, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        transactionDetailsLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        transactionDetailsLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        transactionDetailsLabel1.setText("Bank Account Details");
        transactionDetailsLabel1.setToolTipText("");

        jLabel3.setText("Bank Account Number");

        accountNumberValue.setText("Select a back account");
        accountNumberValue.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel5.setText("Account Holder");

        accountHolderValue.setText("Select a bank account");
        accountHolderValue.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        transactionList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                transactionListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(transactionList);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(transactionDetailsLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(accountNumberValue, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(accountHolderValue, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(transactionDetailsLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(accountNumberValue, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(accountHolderValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(storeNavbarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(readNavbarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteNavbarButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteNavbarButton)
                    .addComponent(readNavbarButton)
                    .addComponent(storeNavbarButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteNavbarButtonMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_deleteNavbarButtonMouseClicked
        System.out.println("Navigating to Delete Transaction");
        this.dispose();
        Delete deleteTransaction = new Delete();
        deleteTransaction.setLocationRelativeTo(null);
        deleteTransaction.setVisible(true);
    }// GEN-LAST:event_deleteNavbarButtonMouseClicked

    private void readNavbarButtonMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_readNavbarButtonMouseClicked
        System.out.println("Navigating to Read Transaction");
        this.dispose();
        Read readTransaction = new Read();
        readTransaction.setLocationRelativeTo(null);
        readTransaction.setVisible(true);
    }// GEN-LAST:event_readNavbarButtonMouseClicked

    private void storeNavbarButtonMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_storeNavbarButtonMouseClicked
        System.out.println("Navigating to Store Transaction");
        this.dispose();
        Store storeTransaction = new Store();
        storeTransaction.setLocationRelativeTo(null);
        storeTransaction.setVisible(true);
    }// GEN-LAST:event_storeNavbarButtonMouseClicked

    private void searchButtonMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_searchButtonMouseClicked
        try {
            BankAccount account = dbTransactions.searchBankAccount(accountNumberInput.getText());
            bankAccountList.setListData(new BankAccount[] { account });
        } catch (Exception e) {

            if (e.getMessage().equals("Account number cannot be null or empty") || e.getMessage().equals("Please enter a valid account number")) {
                bankAccounts = dbTransactions.readBankAccounts();
                bankAccountList.setListData(bankAccounts.toArray(new BankAccount[0]));
                return;
            }

            Popup popup = new Popup(e.getMessage());
            popup.setLocationRelativeTo(null);
            popup.setVisible(true);
        }

    }// GEN-LAST:event_searchButtonMouseClicked

    private void accountNumberInputFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_accountNumberInputFocusLost
        if (accountNumberInput.getText().isEmpty()) {
            accountNumberInput.setText("Enter account number");
        }
    }// GEN-LAST:event_accountNumberInputFocusLost

    private void accountNumberInputMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_accountNumberInputMouseClicked
        if (accountNumberInput.getText().equals("Enter account number")) {
            accountNumberInput.setText("");
        }
    }// GEN-LAST:event_accountNumberInputMouseClicked

    private void transactionListValueChanged(javax.swing.event.ListSelectionEvent evt) {// GEN-FIRST:event_transactionListValueChanged
        Transaction transaction = transactionList.getSelectedValue();
        if (transaction == null) {
            return;
        }

        transactionIdValue.setText(transaction.getTransactionID().toString());
        transactionDateValue.setText(transaction.getTransactionDate().toString());
        transactionAmountValue.setText(Double.toString(transaction.getAmount()));
        senderAccNumValue.setText(transaction.getSenderAccountNumber());
        receiverAccNumValue.setText(transaction.getReceiverAccountNumber());
        transactionTypeValue.setText(transaction.getTransactionType());
    }// GEN-LAST:event_transactionListValueChanged

    private void bankAccountListValueChanged(javax.swing.event.ListSelectionEvent evt) {// GEN-FIRST:event_bankAccountListValueChanged

        transactionList.clearSelection();
        transactionIdValue.setText("Select Transaction");
        transactionDateValue.setText("Select Transaction");
        transactionAmountValue.setText("Select Transaction");
        senderAccNumValue.setText("Select Transaction");
        receiverAccNumValue.setText("Select Transaction");
        transactionTypeValue.setText("Select Transaction");

        BankAccount bankAccount = bankAccountList.getSelectedValue();
        if (bankAccount == null) {
            return;
        }

        accountNumberValue.setText(bankAccount.getAccountNumber());
        accountHolderValue.setText(bankAccount.getAccountHolderName());

        transactions = bankAccount.getTransactions();
        transactionList.setListData(transactions.toArray(new Transaction[0]));
    }// GEN-LAST:event_bankAccountListValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Read.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Read.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Read.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Read.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Read read = new Read();
                read.setLocationRelativeTo(null);
                read.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountHolderValue;
    private javax.swing.JTextField accountNumberInput;
    private javax.swing.JLabel accountNumberValue;
    private javax.swing.JList<BankAccount> bankAccountList;
    private javax.swing.JButton deleteNavbarButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton readNavbarButton;
    private javax.swing.JLabel receiverAccNumLabel;
    private javax.swing.JLabel receiverAccNumValue;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel senderAccNumLabel;
    private javax.swing.JLabel senderAccNumValue;
    private javax.swing.JButton storeNavbarButton;
    private javax.swing.JLabel transactionAmountLabel;
    private javax.swing.JLabel transactionAmountValue;
    private javax.swing.JLabel transactionDateLabel;
    private javax.swing.JLabel transactionDateValue;
    private javax.swing.JLabel transactionDetailsLabel;
    private javax.swing.JLabel transactionDetailsLabel1;
    private javax.swing.JLabel transactionDetailsLabel2;
    private javax.swing.JLabel transactionIdLabel;
    private javax.swing.JLabel transactionIdValue;
    private javax.swing.JList<Transaction> transactionList;
    private javax.swing.JLabel transactionTypeLabel;
    private javax.swing.JLabel transactionTypeValue;
    // End of variables declaration//GEN-END:variables
}
