/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.text.SimpleDateFormat;
import javax.persistence.*;
import java.util.*;

/**
 *
 * @author scott
 */
public class CreateTransaction extends javax.swing.JFrame {

    public void createTransaction() {
        try {
            String transactionDate = this.transactionDateInput.getText();
            String amount = this.amountInput.getText();
            String senderAccNum = this.senderAccNumInput.getText();
            String receiverAccNum = this.receiverAccNumInput.getText();
            String transactionType = this.transactionTypeDisplay.getText();

            if (senderAccNum.equals(receiverAccNum)) {
                throw new Exception("Sender and receiver account numbers cannot be the same");
            }

            Transaction transaction = new Transaction(
                    transactionDate,
                    Double.parseDouble(amount),
                    senderAccNum,
                    receiverAccNum,
                    transactionType);

            if (transaction.checkTransactionDetails() && transaction.isDateFormatted() && transaction.isDateValid()) {

                EntityManagerFactory emf = Persistence.createEntityManagerFactory("$objectdb/db/prac1.odb");

                EntityManager em = emf.createEntityManager();

                em.getTransaction().begin();

                em.persist(transaction);

                em.getTransaction().commit();

                em.close();

                Popup popup = new Popup("Transaction added successfully");
                popup.setLocationRelativeTo(null);
                popup.setVisible(true);

                return;
            }

            throw new Exception("Transaction details are not valid");
        } catch (Exception e) {
            if (e instanceof NumberFormatException) {
                Popup popup = new Popup("Amount must be a valid number");
                popup.setLocationRelativeTo(null);
                popup.setVisible(true);
            } else {
                Popup popup = new Popup(e.getMessage());
                popup.setLocationRelativeTo(null);
                popup.setVisible(true);
            }
        }
    }

    /**
     * Creates new form CreateTransaction
     */
    public CreateTransaction() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NavigateToDeletePage = new javax.swing.JButton();
        NavigateToUpdatePage = new javax.swing.JButton();
        NavigateToReadPage = new javax.swing.JButton();
        NavigateToCreatePage = new javax.swing.JButton();
        Logo = new javax.swing.JLabel();
        transactionDetailsLabel = new javax.swing.JLabel();
        transactionDateLabel = new javax.swing.JLabel();
        transactionDateInput = new javax.swing.JFormattedTextField();
        amountLabel = new javax.swing.JLabel();
        amountInput = new javax.swing.JTextField();
        senderAccNumLabel = new javax.swing.JLabel();
        senderAccNumInput = new javax.swing.JTextField();
        receiverAccNumLabel = new javax.swing.JLabel();
        receiverAccNumInput = new javax.swing.JTextField();
        transactionTypeLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        transactionTypeList = new javax.swing.JList<>();
        transactionTypeDisplay = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NavigateToDeletePage.setText("Delete Transaction");
        NavigateToDeletePage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NavigateToDeletePageMouseClicked(evt);
            }
        });

        NavigateToUpdatePage.setText("Update Transaction");
        NavigateToUpdatePage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NavigateToUpdatePageMouseClicked(evt);
            }
        });

        NavigateToReadPage.setText("Read Transaction");
        NavigateToReadPage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NavigateToReadPageMouseClicked(evt);
            }
        });

        NavigateToCreatePage.setText("Create Transaction");
        NavigateToCreatePage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NavigateToCreatePageMouseClicked(evt);
            }
        });

        Logo.setText("FinGuard Solutions");

        transactionDetailsLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        transactionDetailsLabel.setText("Please enter the following transaction details");

        transactionDateLabel.setText("Transaction Date");

        transactionDateInput.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        transactionDateInput.setText("dd/mm/yyyy");
        transactionDateInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                transactionDateInputFocusLost(evt);
            }
        });
        transactionDateInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transactionDateInputMouseClicked(evt);
            }
        });

        amountLabel.setText("Amount");

        amountInput.setText("R 0000.00");
        amountInput.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        amountInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                amountInputFocusLost(evt);
            }
        });
        amountInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                amountInputMouseClicked(evt);
            }
        });

        senderAccNumLabel.setText("Sender Account Number");

        senderAccNumInput.setText("123456789");
        senderAccNumInput.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        senderAccNumInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                senderAccNumInputFocusLost(evt);
            }
        });
        senderAccNumInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                senderAccNumInputMouseClicked(evt);
            }
        });

        receiverAccNumLabel.setText("Receiver Account Number");

        receiverAccNumInput.setText("123456789");
        receiverAccNumInput.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        receiverAccNumInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                receiverAccNumInputFocusLost(evt);
            }
        });
        receiverAccNumInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                receiverAccNumInputMouseClicked(evt);
            }
        });

        transactionTypeLabel.setText("Transaction Type");

        transactionTypeList.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        transactionTypeList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Deposit", "Withdrawl", "Transfer" };

            public int getSize() {
                return strings.length;
            }

            public String getElementAt(int i) {
                return strings[i];
            }
        });
        transactionTypeList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        transactionTypeList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                transactionTypeListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(transactionTypeList);

        transactionTypeDisplay.setText("None selected");

        saveButton.setText("Add transaction");
        saveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                false)
                                                        .addComponent(saveButton,
                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(transactionDateLabel)
                                                                        .addComponent(amountLabel)
                                                                        .addComponent(senderAccNumLabel)
                                                                        .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                false)
                                                                                .addComponent(receiverAccNumInput,
                                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(senderAccNumInput,
                                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(amountInput,
                                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(transactionDateInput,
                                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        191,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addComponent(receiverAccNumLabel))
                                                                .addGap(79, 79, 79)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        false)
                                                                        .addComponent(transactionTypeLabel)
                                                                        .addComponent(jScrollPane1)
                                                                        .addComponent(transactionTypeDisplay,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                147,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(Logo)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63,
                                                        Short.MAX_VALUE)
                                                .addComponent(NavigateToCreatePage)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(NavigateToReadPage)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(NavigateToUpdatePage)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NavigateToDeletePage)
                                .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(transactionDetailsLabel)
                                .addGap(93, 93, 93)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(NavigateToDeletePage)
                                        .addComponent(NavigateToUpdatePage)
                                        .addComponent(NavigateToReadPage)
                                        .addComponent(NavigateToCreatePage)
                                        .addComponent(Logo))
                                .addGap(18, 18, 18)
                                .addComponent(transactionDetailsLabel)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(transactionDateLabel)
                                        .addComponent(transactionTypeLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(transactionDateInput,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(amountLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(amountInput, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(senderAccNumLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(senderAccNumInput, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(receiverAccNumLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(receiverAccNumInput,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(transactionTypeDisplay,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(91, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NavigateToCreatePageMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_NavigateToCreatePageMouseClicked
        System.out.println("Navigating to Create Transaction");
        this.dispose();
        CreateTransaction createTransaction = new CreateTransaction();
        createTransaction.setLocationRelativeTo(null);
        createTransaction.setVisible(true);
    }// GEN-LAST:event_NavigateToCreatePageMouseClicked

    private void NavigateToReadPageMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_NavigateToReadPageMouseClicked
        System.out.println("Navigating to Read Transaction");
        this.dispose();
        ReadTransaction readTransaction = new ReadTransaction();
        readTransaction.setLocationRelativeTo(null);
        readTransaction.setVisible(true);
    }// GEN-LAST:event_NavigateToReadPageMouseClicked

    private void NavigateToUpdatePageMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_NavigateToUpdatePageMouseClicked
        System.out.println("Navigating to Update Transaction");
        this.dispose();
        UpdateTransaction updateTransaction = new UpdateTransaction();
        updateTransaction.setLocationRelativeTo(null);
        updateTransaction.setVisible(true);
    }// GEN-LAST:event_NavigateToUpdatePageMouseClicked

    private void NavigateToDeletePageMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_NavigateToDeletePageMouseClicked
        System.out.println("Navigating to Delete Transaction");
        this.dispose();
        DeleteTransaction deleteTransaction = new DeleteTransaction();
        deleteTransaction.setLocationRelativeTo(null);
        deleteTransaction.setVisible(true);
    }// GEN-LAST:event_NavigateToDeletePageMouseClicked

    private void transactionDateInputMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_transactionDateInputMouseClicked
        if (this.transactionDateInput.getText().equals("dd/mm/yyyy"))
            this.transactionDateInput.setText("");
    }// GEN-LAST:event_transactionDateInputMouseClicked

    private void amountInputMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_amountInputMouseClicked
        if (this.amountInput.getText().equals("R 0000.00"))
            this.amountInput.setText("");
    }// GEN-LAST:event_amountInputMouseClicked

    private void senderAccNumInputMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_senderAccNumInputMouseClicked
        if (this.senderAccNumInput.getText().equals("123456789"))
            this.senderAccNumInput.setText("");
    }// GEN-LAST:event_senderAccNumInputMouseClicked

    private void receiverAccNumInputMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_receiverAccNumInputMouseClicked
        if (this.receiverAccNumInput.getText().equals("123456789"))
            this.receiverAccNumInput.setText("");
    }// GEN-LAST:event_receiverAccNumInputMouseClicked

    private void transactionTypeListValueChanged(javax.swing.event.ListSelectionEvent evt) {// GEN-FIRST:event_transactionTypeListValueChanged
        this.transactionTypeDisplay.setText(this.transactionTypeList.getSelectedValue());
    }// GEN-LAST:event_transactionTypeListValueChanged

    private void saveButtonMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_saveButtonMouseClicked
        createTransaction();
    }// GEN-LAST:event_saveButtonMouseClicked

    private void transactionDateInputFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_transactionDateInputFocusLost
        if (this.transactionDateInput.getText().equals(""))
            this.transactionDateInput.setText("dd/mm/yyyy");
    }// GEN-LAST:event_transactionDateInputFocusLost

    private void amountInputFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_amountInputFocusLost
        if (this.amountInput.getText().equals(""))
            this.amountInput.setText("R 0000.00");
    }// GEN-LAST:event_amountInputFocusLost

    private void senderAccNumInputFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_senderAccNumInputFocusLost
        if (this.senderAccNumInput.getText().equals(""))
            this.senderAccNumInput.setText("123456789");
    }// GEN-LAST:event_senderAccNumInputFocusLost

    private void receiverAccNumInputFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_receiverAccNumInputFocusLost
        if (this.receiverAccNumInput.getText().equals(""))
            this.receiverAccNumInput.setText("123456789");
    }// GEN-LAST:event_receiverAccNumInputFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateTransaction.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateTransaction.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateTransaction.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateTransaction.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateTransaction().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JButton NavigateToCreatePage;
    private javax.swing.JButton NavigateToDeletePage;
    private javax.swing.JButton NavigateToReadPage;
    private javax.swing.JButton NavigateToUpdatePage;
    private javax.swing.JTextField amountInput;
    private javax.swing.JLabel amountLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField receiverAccNumInput;
    private javax.swing.JLabel receiverAccNumLabel;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField senderAccNumInput;
    private javax.swing.JLabel senderAccNumLabel;
    private javax.swing.JFormattedTextField transactionDateInput;
    private javax.swing.JLabel transactionDateLabel;
    private javax.swing.JLabel transactionDetailsLabel;
    private javax.swing.JLabel transactionTypeDisplay;
    private javax.swing.JLabel transactionTypeLabel;
    private javax.swing.JList<String> transactionTypeList;
    // End of variables declaration//GEN-END:variables
}
