-- Drop tables if they exist
DROP TABLE IF EXISTS DegreeProgram CASCADE;
DROP TABLE IF EXISTS Course CASCADE;
DROP TABLE IF EXISTS Student CASCADE;
DROP TABLE IF EXISTS Undergraduate CASCADE;
DROP TABLE IF EXISTS Supervisor CASCADE;
DROP TABLE IF EXISTS Postgraduate CASCADE;

-- Drop functions if they exist
DROP FUNCTION IF EXISTS personFullName(CHAR(6)) CASCADE;
DROP FUNCTION IF EXISTS ageInYears(CHAR(6)) CASCADE;
DROP FUNCTION IF EXISTS isRegisteredFor(CHAR(6), CourseCodeName) CASCADE;
DROP FUNCTION IF EXISTS isFinalYearStudent(CHAR(6)) CASCADE;
DROP FUNCTION IF EXISTS isFullTime(CHAR(6)) CASCADE;
DROP FUNCTION IF EXISTS isPartTime(CHAR(6)) CASCADE;

-- Drop types if they exist
DROP TYPE IF EXISTS CourseCodeName CASCADE;
DROP TYPE IF EXISTS CustomCategory CASCADE;
DROP TYPE IF EXISTS Title CASCADE;

-- Drop sequences if they exist
DROP SEQUENCE IF EXISTS StudentID CASCADE;
DROP SEQUENCE IF EXISTS DegreeKey CASCADE;
DROP SEQUENCE IF EXISTS CourseKey CASCADE;

