/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.prac4;

/**
 *
 * @author scott
 */
public class Delete_Film extends javax.swing.JFrame
{

    /**
     * Creates new form Delete_Film
     */
    public Delete_Film()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        Delete_Film_Container = new javax.swing.JPanel();
        Delete_Film_Label = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Delete_Film_Title = new javax.swing.JTextField();
        Title_output = new javax.swing.JTextField();
        Delete_Film = new javax.swing.JButton();
        Back_Button = new javax.swing.JButton();
        Delete_Check = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Delete_Movie_Dropbox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Film_ID = new javax.swing.JTextField();
        Rating_Output = new javax.swing.JTextField();
        Description_Output = new javax.swing.JTextField();
        Language = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Delete_Film_Container.setBackground(new java.awt.Color(255, 255, 255));

        Delete_Film_Label.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Delete_Film_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Delete_Film_Label.setText("Add Film");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        Delete_Film_Title.setText("Title");
        Delete_Film_Title.setPreferredSize(new java.awt.Dimension(250, 50));
        Delete_Film_Title.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                Delete_Film_TitleMouseClicked(evt);
            }
        });
        Delete_Film_Title.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                Delete_Film_TitleActionPerformed(evt);
            }
        });

        Title_output.setText("Title");
        Title_output.setPreferredSize(new java.awt.Dimension(250, 50));
        Title_output.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                Title_outputMouseClicked(evt);
            }
        });

        Delete_Film.setText("Delete");
        Delete_Film.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                Delete_FilmActionPerformed(evt);
            }
        });

        Back_Button.setText("Back");
        Back_Button.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                Back_ButtonActionPerformed(evt);
            }
        });

        Delete_Check.setText("Validate Movie Exists");
        Delete_Check.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                Delete_CheckActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Or");

        Delete_Movie_Dropbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Delete_Movie_Dropbox.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                Delete_Movie_DropboxMouseClicked(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Verify the film is in the database");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Film Information");

        Film_ID.setText("Film ID");
        Film_ID.setPreferredSize(new java.awt.Dimension(250, 50));
        Film_ID.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                Film_IDMouseClicked(evt);
            }
        });

        Rating_Output.setText("Rating");
        Rating_Output.setPreferredSize(new java.awt.Dimension(250, 50));
        Rating_Output.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                Rating_OutputMouseClicked(evt);
            }
        });

        Description_Output.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Description_Output.setText("Description");
        Description_Output.setPreferredSize(new java.awt.Dimension(250, 50));
        Description_Output.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                Description_OutputMouseClicked(evt);
            }
        });

        Language.setText("Language");
        Language.setPreferredSize(new java.awt.Dimension(250, 50));
        Language.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                LanguageMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Delete_Film_ContainerLayout = new javax.swing.GroupLayout(Delete_Film_Container);
        Delete_Film_Container.setLayout(Delete_Film_ContainerLayout);
        Delete_Film_ContainerLayout.setHorizontalGroup(
            Delete_Film_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(Delete_Film_ContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Delete_Film_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Delete_Film_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(Delete_Film_ContainerLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addGroup(Delete_Film_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Delete_Film_ContainerLayout.createSequentialGroup()
                                .addComponent(Delete_Film_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Delete_Movie_Dropbox, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Delete_Check, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(Delete_Film_ContainerLayout.createSequentialGroup()
                                .addGroup(Delete_Film_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Title_output, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Language, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Delete_Film, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(Delete_Film_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Rating_Output, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Film_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Back_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(Description_Output, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 134, Short.MAX_VALUE)))
                .addContainerGap())
        );
        Delete_Film_ContainerLayout.setVerticalGroup(
            Delete_Film_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Delete_Film_ContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Delete_Film_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Delete_Film_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Delete_Film_Title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(Delete_Movie_Dropbox, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Delete_Check, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Delete_Film_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Title_output, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Film_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Description_Output, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Delete_Film_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rating_Output, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Language, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Delete_Film_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Delete_Film, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Back_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Delete_Film_Container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Delete_Film_Container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Delete_Film_TitleMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_Delete_Film_TitleMouseClicked
    {//GEN-HEADEREND:event_Delete_Film_TitleMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Delete_Film_TitleMouseClicked

    private void Delete_Film_TitleActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Delete_Film_TitleActionPerformed
    {//GEN-HEADEREND:event_Delete_Film_TitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Delete_Film_TitleActionPerformed

    private void Title_outputMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_Title_outputMouseClicked
    {//GEN-HEADEREND:event_Title_outputMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Title_outputMouseClicked

    private void Delete_FilmActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Delete_FilmActionPerformed
    {//GEN-HEADEREND:event_Delete_FilmActionPerformed

    }//GEN-LAST:event_Delete_FilmActionPerformed

    private void Back_ButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Back_ButtonActionPerformed
    {//GEN-HEADEREND:event_Back_ButtonActionPerformed
        Films form = new Films();
        form.setSize(800, 650);
        form.setLocationRelativeTo(null);
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Back_ButtonActionPerformed

    private void Film_IDMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_Film_IDMouseClicked
    {//GEN-HEADEREND:event_Film_IDMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Film_IDMouseClicked

    private void Rating_OutputMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_Rating_OutputMouseClicked
    {//GEN-HEADEREND:event_Rating_OutputMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Rating_OutputMouseClicked

    private void Description_OutputMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_Description_OutputMouseClicked
    {//GEN-HEADEREND:event_Description_OutputMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Description_OutputMouseClicked

    private void Delete_Movie_DropboxMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_Delete_Movie_DropboxMouseClicked
    {//GEN-HEADEREND:event_Delete_Movie_DropboxMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Delete_Movie_DropboxMouseClicked

    private void Delete_CheckActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Delete_CheckActionPerformed
    {//GEN-HEADEREND:event_Delete_CheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Delete_CheckActionPerformed

    private void LanguageMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_LanguageMouseClicked
    {//GEN-HEADEREND:event_LanguageMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_LanguageMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Delete_Film.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Delete_Film.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Delete_Film.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Delete_Film.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Delete_Film().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_Button;
    private javax.swing.JButton Delete_Check;
    private javax.swing.JButton Delete_Film;
    private javax.swing.JPanel Delete_Film_Container;
    private javax.swing.JLabel Delete_Film_Label;
    private javax.swing.JTextField Delete_Film_Title;
    private javax.swing.JComboBox<String> Delete_Movie_Dropbox;
    private javax.swing.JTextField Description_Output;
    private javax.swing.JTextField Film_ID;
    private javax.swing.JTextField Language;
    private javax.swing.JTextField Rating_Output;
    private javax.swing.JTextField Title_output;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
