/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.prac4;

import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author scott
 */
public class Films extends javax.swing.JFrame
{

    /**
     * Creates new form Films
     */
    public Films()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        Homepage_Container = new javax.swing.JPanel();
        Home_Page = new javax.swing.JButton();
        Genre_Button = new javax.swing.JButton();
        Staff_Page = new javax.swing.JButton();
        Films_Page = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Clients_Page = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        Searchbar = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        Staff_Info_Table1 = new javax.swing.JTable();
        Homepage_Container1 = new javax.swing.JPanel();
        Films_SearchBar = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        Films_Info_Table = new javax.swing.JTable();
        Add_Film_Page = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        Home_Page1 = new javax.swing.JButton();
        Staff_Page1 = new javax.swing.JButton();
        Films_Page1 = new javax.swing.JButton();
        Reports_Page = new javax.swing.JButton();
        Notifications_Page = new javax.swing.JButton();
        Exit1 = new javax.swing.JButton();
        Delete_Film_Page = new javax.swing.JButton();

        Homepage_Container.setBackground(new java.awt.Color(255, 255, 255));

        Home_Page.setText("Home");
        Home_Page.setPreferredSize(new java.awt.Dimension(75, 25));
        Home_Page.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                Home_PageActionPerformed(evt);
            }
        });

        Genre_Button.setText("Genre");
        Genre_Button.setPreferredSize(new java.awt.Dimension(75, 25));

        Staff_Page.setText("Staff");
        Staff_Page.setPreferredSize(new java.awt.Dimension(75, 25));

        Films_Page.setText("Films");
        Films_Page.setPreferredSize(new java.awt.Dimension(75, 25));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Staff");

        Clients_Page.setText("Clients");
        Clients_Page.setPreferredSize(new java.awt.Dimension(75, 25));
        Clients_Page.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                Clients_PageActionPerformed(evt);
            }
        });

        Exit.setText("Exit");
        Exit.setPreferredSize(new java.awt.Dimension(75, 25));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setAlignmentX(0.0F);
        jSeparator1.setAlignmentY(0.0F);

        Searchbar.setText("Search...");

        Staff_Info_Table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String []
            {
                "Name", "Surname", "Address", "Adress 2", "District", "City", "Postal Code", "Phone", "Store", "Active"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        Staff_Info_Table1.setGridColor(new java.awt.Color(0, 0, 0));
        Staff_Info_Table1.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(Staff_Info_Table1);

        javax.swing.GroupLayout Homepage_ContainerLayout = new javax.swing.GroupLayout(Homepage_Container);
        Homepage_Container.setLayout(Homepage_ContainerLayout);
        Homepage_ContainerLayout.setHorizontalGroup(
            Homepage_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Homepage_ContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Homepage_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Home_Page, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Staff_Page, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Genre_Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Clients_Page, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Films_Page, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Homepage_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Searchbar)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE))
                .addContainerGap())
        );
        Homepage_ContainerLayout.setVerticalGroup(
            Homepage_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(Homepage_ContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Homepage_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Homepage_ContainerLayout.createSequentialGroup()
                        .addComponent(Searchbar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2))
                    .addGroup(Homepage_ContainerLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(Home_Page, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(Staff_Page, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(Films_Page, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(Genre_Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(Clients_Page, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                        .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Homepage_Container1.setBackground(new java.awt.Color(255, 255, 255));

        Films_SearchBar.setText("Search...");
        Films_SearchBar.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                Films_SearchBarMouseClicked(evt);
            }
        });
        Films_SearchBar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                Films_SearchBarActionPerformed(evt);
            }
        });
        Films_SearchBar.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                Films_SearchBarKeyReleased(evt);
            }
        });

        Films_Info_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object[][]
            {
                {"The Shawshank Redemption", "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.", 1994, "9.3", 3.99, 19.99},
                {"The Godfather", "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.", 1972, "9.2", 3.99, 19.99},
                {"The Dark Knight", "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.", 2008, "9.0", 3.99, 19.99},
                {"Pulp Fiction", "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.", 1994, "8.9", 3.99, 19.99}
            },
            new String []
            {
                "Title", "Description", "Year", "Rating", "Rental Cost", "Replacement Cost"
            }

        )
        {
            boolean[] canEdit = new boolean []
            {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        Films_Info_Table.setGridColor(new java.awt.Color(0, 0, 0));
        Films_Info_Table.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setViewportView(Films_Info_Table);

        Add_Film_Page.setText("Add Film");
        Add_Film_Page.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                Add_Film_PageActionPerformed(evt);
            }
        });

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setAlignmentX(0.0F);
        jSeparator3.setAlignmentY(0.0F);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Films");

        Home_Page1.setText("Home");
        Home_Page1.setPreferredSize(new java.awt.Dimension(75, 25));
        Home_Page1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                Home_Page1ActionPerformed(evt);
            }
        });

        Staff_Page1.setText("Staff");
        Staff_Page1.setPreferredSize(new java.awt.Dimension(75, 25));
        Staff_Page1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                Staff_Page1ActionPerformed(evt);
            }
        });

        Films_Page1.setText("Films");
        Films_Page1.setPreferredSize(new java.awt.Dimension(75, 25));
        Films_Page1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                Films_Page1ActionPerformed(evt);
            }
        });

        Reports_Page.setText("Reports");
        Reports_Page.setPreferredSize(new java.awt.Dimension(75, 25));
        Reports_Page.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                Reports_PageActionPerformed(evt);
            }
        });

        Notifications_Page.setText("Notifications");
        Notifications_Page.setPreferredSize(new java.awt.Dimension(75, 25));
        Notifications_Page.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                Notifications_PageActionPerformed(evt);
            }
        });

        Exit1.setText("Exit");
        Exit1.setPreferredSize(new java.awt.Dimension(75, 25));
        Exit1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                Exit1ActionPerformed(evt);
            }
        });

        Delete_Film_Page.setText("Delete Film");
        Delete_Film_Page.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                Delete_Film_PageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Homepage_Container1Layout = new javax.swing.GroupLayout(Homepage_Container1);
        Homepage_Container1.setLayout(Homepage_Container1Layout);
        Homepage_Container1Layout.setHorizontalGroup(
            Homepage_Container1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Homepage_Container1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Homepage_Container1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Home_Page1, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                    .addComponent(Staff_Page1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Reports_Page, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Films_Page1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Exit1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Notifications_Page, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Homepage_Container1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE)
                    .addGroup(Homepage_Container1Layout.createSequentialGroup()
                        .addComponent(Films_SearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Add_Film_Page, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Delete_Film_Page, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)))
                .addContainerGap())
        );
        Homepage_Container1Layout.setVerticalGroup(
            Homepage_Container1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Homepage_Container1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Homepage_Container1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Homepage_Container1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(Home_Page1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(Staff_Page1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(Films_Page1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(Reports_Page, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(Notifications_Page, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                        .addComponent(Exit1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Homepage_Container1Layout.createSequentialGroup()
                        .addGroup(Homepage_Container1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Films_SearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Homepage_Container1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Add_Film_Page, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Delete_Film_Page, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jSeparator3)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Homepage_Container1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Homepage_Container1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Home_PageActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Home_PageActionPerformed
    {//GEN-HEADEREND:event_Home_PageActionPerformed

    }//GEN-LAST:event_Home_PageActionPerformed

    private void Clients_PageActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Clients_PageActionPerformed
    {//GEN-HEADEREND:event_Clients_PageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Clients_PageActionPerformed

    private void Add_Film_PageActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Add_Film_PageActionPerformed
    {//GEN-HEADEREND:event_Add_Film_PageActionPerformed
        Add_Film form = new Add_Film();
        form.setSize(800, 650);
        form.setLocationRelativeTo(null);
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Add_Film_PageActionPerformed

    private void Home_Page1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Home_Page1ActionPerformed
    {//GEN-HEADEREND:event_Home_Page1ActionPerformed
        HomePage form = new HomePage();
        form.setSize(800, 650);
        form.setLocationRelativeTo(null);
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Home_Page1ActionPerformed

    private void Staff_Page1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Staff_Page1ActionPerformed
    {//GEN-HEADEREND:event_Staff_Page1ActionPerformed
        Staff form = new Staff();
        form.setSize(800, 650);
        form.setLocationRelativeTo(null);
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Staff_Page1ActionPerformed

    private void Films_Page1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Films_Page1ActionPerformed
    {//GEN-HEADEREND:event_Films_Page1ActionPerformed

    }//GEN-LAST:event_Films_Page1ActionPerformed

    private void Reports_PageActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Reports_PageActionPerformed
    {//GEN-HEADEREND:event_Reports_PageActionPerformed
        Reports form = new Reports();
        form.setSize(800, 650);
        form.setLocationRelativeTo(null);
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Reports_PageActionPerformed

    private void Notifications_PageActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Notifications_PageActionPerformed
    {//GEN-HEADEREND:event_Notifications_PageActionPerformed
        Notifications form = new Notifications();
        form.setSize(800, 650);
        form.setLocationRelativeTo(null);
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Notifications_PageActionPerformed

    private void Exit1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Exit1ActionPerformed
    {//GEN-HEADEREND:event_Exit1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_Exit1ActionPerformed

    private void Films_SearchBarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Films_SearchBarActionPerformed
    {//GEN-HEADEREND:event_Films_SearchBarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Films_SearchBarActionPerformed

    private void Films_SearchBarKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_Films_SearchBarKeyReleased
    {//GEN-HEADEREND:event_Films_SearchBarKeyReleased
        String searchValue = Films_SearchBar.getText();
        DefaultTableModel tableModel = (DefaultTableModel) Films_Info_Table.getModel();
        TableRowSorter<DefaultTableModel> tableRowSorter = new TableRowSorter<>(tableModel);
        Films_Info_Table.setRowSorter(tableRowSorter);
        if (searchValue.trim().length() == 0)
        {
            tableRowSorter.setRowFilter(null);
        } else
        {
            tableRowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + searchValue));
        }
    }//GEN-LAST:event_Films_SearchBarKeyReleased

    private void Films_SearchBarMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_Films_SearchBarMouseClicked
    {//GEN-HEADEREND:event_Films_SearchBarMouseClicked
        if (Films_SearchBar.getText().equals("Search..."))
        {
            Films_SearchBar.setText("");
        }
    }//GEN-LAST:event_Films_SearchBarMouseClicked

    private void Delete_Film_PageActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Delete_Film_PageActionPerformed
    {//GEN-HEADEREND:event_Delete_Film_PageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Delete_Film_PageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Films.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Films.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Films.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Films.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Films().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_Film_Page;
    private javax.swing.JButton Clients_Page;
    private javax.swing.JButton Delete_Film_Page;
    private javax.swing.JButton Exit;
    private javax.swing.JButton Exit1;
    private javax.swing.JTable Films_Info_Table;
    private javax.swing.JButton Films_Page;
    private javax.swing.JButton Films_Page1;
    private javax.swing.JTextField Films_SearchBar;
    private javax.swing.JButton Genre_Button;
    private javax.swing.JButton Home_Page;
    private javax.swing.JButton Home_Page1;
    private javax.swing.JPanel Homepage_Container;
    private javax.swing.JPanel Homepage_Container1;
    private javax.swing.JButton Notifications_Page;
    private javax.swing.JButton Reports_Page;
    private javax.swing.JTextField Searchbar;
    private javax.swing.JTable Staff_Info_Table1;
    private javax.swing.JButton Staff_Page;
    private javax.swing.JButton Staff_Page1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
