/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.prac4;

import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author scott
 */
public class Notifications extends javax.swing.JFrame
{

    /**
     * Creates new form Notifications
     */
    public Notifications()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        Homepage_Container = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        Home_Page = new javax.swing.JButton();
        Staff_Page = new javax.swing.JButton();
        Films_Page = new javax.swing.JButton();
        Reports_Page = new javax.swing.JButton();
        Notifications_Page = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        SearchBar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Notifications_List_Clients_Table = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        SearchBar_Inactive = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        ClientsTableInactive = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        Add_FName = new javax.swing.JTextField();
        ADD_SName = new javax.swing.JTextField();
        Add_Email = new javax.swing.JTextField();
        Add_Active = new javax.swing.JTextField();
        Add_Back_Button = new javax.swing.JButton();
        Add_Button = new javax.swing.JButton();
        Add_Store_ID = new javax.swing.JComboBox<>();
        Add_Address1 = new javax.swing.JTextField();
        Add_Address2 = new javax.swing.JTextField();
        Add_District = new javax.swing.JTextField();
        Add_Postal_Code = new javax.swing.JTextField();
        Add_City_Dropbox = new javax.swing.JComboBox<>();
        Add_Phone_Number = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        Update_Cust_ID = new javax.swing.JTextField();
        Update_Store_ID_Output = new javax.swing.JTextField();
        Update_FName_Output = new javax.swing.JTextField();
        Update_SName_Output = new javax.swing.JTextField();
        Update_Email_Output = new javax.swing.JTextField();
        Update_Active_Output = new javax.swing.JTextField();
        Update_Button = new javax.swing.JButton();
        Update_Back_Button = new javax.swing.JButton();
        Update_Check_Client_Button = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Address1_Output = new javax.swing.JTextField();
        Address2_Output = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Update_StoreID_Input = new javax.swing.JTextField();
        Update_FName_Input = new javax.swing.JTextField();
        Update_LName_Input = new javax.swing.JTextField();
        Update_Email_Input = new javax.swing.JTextField();
        Update_Active_Input = new javax.swing.JTextField();
        Update_Address1_Input = new javax.swing.JTextField();
        Update_Address2_Input = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        Delete_FName = new javax.swing.JTextField();
        Delete_SName = new javax.swing.JTextField();
        Delete_Email = new javax.swing.JTextField();
        Delete_Button = new javax.swing.JButton();
        Delete_Back_Button = new javax.swing.JButton();
        Delete_Cust_ID = new javax.swing.JTextField();
        Delete_Client_Check_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Homepage_Container.setBackground(new java.awt.Color(255, 255, 255));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setAlignmentX(0.0F);
        jSeparator1.setAlignmentY(0.0F);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Notifications");

        Home_Page.setText("Home");
        Home_Page.setPreferredSize(new java.awt.Dimension(75, 25));
        Home_Page.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                Home_PageActionPerformed(evt);
            }
        });

        Staff_Page.setText("Staff");
        Staff_Page.setPreferredSize(new java.awt.Dimension(75, 25));
        Staff_Page.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                Staff_PageActionPerformed(evt);
            }
        });

        Films_Page.setText("Films");
        Films_Page.setPreferredSize(new java.awt.Dimension(75, 25));
        Films_Page.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                Films_PageActionPerformed(evt);
            }
        });

        Reports_Page.setText("Reports");
        Reports_Page.setPreferredSize(new java.awt.Dimension(75, 25));
        Reports_Page.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                Reports_PageActionPerformed(evt);
            }
        });

        Notifications_Page.setText("Notifications");
        Notifications_Page.setPreferredSize(new java.awt.Dimension(75, 25));
        Notifications_Page.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                Notifications_PageActionPerformed(evt);
            }
        });

        Exit.setText("Exit");
        Exit.setPreferredSize(new java.awt.Dimension(75, 25));
        Exit.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ExitActionPerformed(evt);
            }
        });

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        SearchBar.setText("Search...");
        SearchBar.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                SearchBarMouseClicked(evt);
            }
        });
        SearchBar.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                SearchBarKeyReleased(evt);
            }
        });

        Notifications_List_Clients_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object[][]
            {
                {"John", "Doe", "johndoe@example.com", null, null},
                {"Jane", "Doe", "janedoe@example.com", null, null},
                {"Bob", "Smith", "bobsmith@example.com", null, null},
                {"Alice", "Jones", "alicejones@example.com", null, null}
            },
            new String[]
            {
                "First Name", "Last Name", "Email", "Address 1", "Address 2"
            }

        )
        {
            boolean[] canEdit = new boolean []
            {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        Notifications_List_Clients_Table.setGridColor(new java.awt.Color(0, 0, 0));
        Notifications_List_Clients_Table.setOpaque(false);
        jScrollPane1.setViewportView(Notifications_List_Clients_Table);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
                    .addComponent(SearchBar))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("List Clients Active", jPanel1);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        SearchBar_Inactive.setText("Search...");

        ClientsTableInactive.setModel(new javax.swing.table.DefaultTableModel(
            new Object[][]
            {
                {"John", "Doe", "johndoe@example.com", null, null},
                {"Jane", "Doe", "janedoe@example.com", null, null},
                {"Bob", "Smith", "bobsmith@example.com", null, null},
                {"Alice", "Jones", "alicejones@example.com", null, null}
            },
            new String[]
            {
                "First Name", "Last Name", "Email", "Address 1", "Address 2"
            }

        )
    );
    jScrollPane2.setViewportView(ClientsTableInactive);

    javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
    jPanel7.setLayout(jPanel7Layout);
    jPanel7Layout.setHorizontalGroup(
        jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
                .addComponent(SearchBar_Inactive))
            .addContainerGap())
    );
    jPanel7Layout.setVerticalGroup(
        jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel7Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(SearchBar_Inactive, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
            .addContainerGap())
    );

    javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
    jPanel5.setLayout(jPanel5Layout);
    jPanel5Layout.setHorizontalGroup(
        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    jPanel5Layout.setVerticalGroup(
        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    jTabbedPane1.addTab("List Clients Inactive", jPanel5);

    jPanel2.setBackground(new java.awt.Color(255, 255, 255));
    jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

    Add_FName.setText("First Name");
    Add_FName.addMouseListener(new java.awt.event.MouseAdapter()
    {
        public void mouseClicked(java.awt.event.MouseEvent evt)
        {
            Add_FNameMouseClicked(evt);
        }
    });
    Add_FName.addActionListener(new java.awt.event.ActionListener()
    {
        public void actionPerformed(java.awt.event.ActionEvent evt)
        {
            Add_FNameActionPerformed(evt);
        }
    });

    ADD_SName.setText("Last Name");
    ADD_SName.addMouseListener(new java.awt.event.MouseAdapter()
    {
        public void mouseClicked(java.awt.event.MouseEvent evt)
        {
            ADD_SNameMouseClicked(evt);
        }
    });
    ADD_SName.addActionListener(new java.awt.event.ActionListener()
    {
        public void actionPerformed(java.awt.event.ActionEvent evt)
        {
            ADD_SNameActionPerformed(evt);
        }
    });

    Add_Email.setText("Email Address");
    Add_Email.addMouseListener(new java.awt.event.MouseAdapter()
    {
        public void mouseClicked(java.awt.event.MouseEvent evt)
        {
            Add_EmailMouseClicked(evt);
        }
    });

    Add_Active.setText("Active");
    Add_Active.addMouseListener(new java.awt.event.MouseAdapter()
    {
        public void mouseClicked(java.awt.event.MouseEvent evt)
        {
            Add_ActiveMouseClicked(evt);
        }
    });

    Add_Back_Button.setText("Back");
    Add_Back_Button.addActionListener(new java.awt.event.ActionListener()
    {
        public void actionPerformed(java.awt.event.ActionEvent evt)
        {
            Add_Back_ButtonActionPerformed(evt);
        }
    });

    Add_Button.setText("Add Client");
    Add_Button.addActionListener(new java.awt.event.ActionListener()
    {
        public void actionPerformed(java.awt.event.ActionEvent evt)
        {
            Add_ButtonActionPerformed(evt);
        }
    });

    Add_Store_ID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Store ID", "Item 2", "Item 3", "Item 4" }));

    Add_Address1.setText("Address 1");
    Add_Address1.addMouseListener(new java.awt.event.MouseAdapter()
    {
        public void mouseClicked(java.awt.event.MouseEvent evt)
        {
            Add_Address1MouseClicked(evt);
        }
    });

    Add_Address2.setText("Address 2");
    Add_Address2.addMouseListener(new java.awt.event.MouseAdapter()
    {
        public void mouseClicked(java.awt.event.MouseEvent evt)
        {
            Add_Address2MouseClicked(evt);
        }
    });

    Add_District.setText("District");
    Add_District.addMouseListener(new java.awt.event.MouseAdapter()
    {
        public void mouseClicked(java.awt.event.MouseEvent evt)
        {
            Add_DistrictMouseClicked(evt);
        }
    });

    Add_Postal_Code.setText("Postal Code");
    Add_Postal_Code.addMouseListener(new java.awt.event.MouseAdapter()
    {
        public void mouseClicked(java.awt.event.MouseEvent evt)
        {
            Add_Postal_CodeMouseClicked(evt);
        }
    });

    Add_City_Dropbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "City", "Item 2", "Item 3", "Item 4" }));

    Add_Phone_Number.setText("Phone Number");
    Add_Phone_Number.addMouseListener(new java.awt.event.MouseAdapter()
    {
        public void mouseClicked(java.awt.event.MouseEvent evt)
        {
            Add_Phone_NumberMouseClicked(evt);
        }
    });

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addGap(6, 6, 6)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(Add_Email, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                .addComponent(ADD_SName, javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Add_FName, javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Add_Store_ID, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Add_Active)
                .addComponent(Add_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(Add_Postal_Code, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                .addComponent(Add_District)
                .addComponent(Add_Address2)
                .addComponent(Add_Address1)
                .addComponent(Add_City_Dropbox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Add_Back_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap())
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
            .addContainerGap(171, Short.MAX_VALUE)
            .addComponent(Add_Phone_Number, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(160, 160, 160))
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(Add_Address1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(Add_Store_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(Add_FName, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(Add_Address2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(ADD_SName, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(Add_District, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(Add_Email, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addComponent(Add_City_Dropbox))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(Add_Active, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(Add_Postal_Code, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(Add_Phone_Number, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(Add_Back_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(Add_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(163, 163, 163))
    );

    jTabbedPane1.addTab("Add Clients", jPanel2);

    jPanel3.setBackground(new java.awt.Color(255, 255, 255));
    jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

    Update_Cust_ID.setText("Customer ID (Required)");
    Update_Cust_ID.setPreferredSize(new java.awt.Dimension(150, 50));
    Update_Cust_ID.addMouseListener(new java.awt.event.MouseAdapter()
    {
        public void mouseClicked(java.awt.event.MouseEvent evt)
        {
            Update_Cust_IDMouseClicked(evt);
        }
    });
    Update_Cust_ID.addActionListener(new java.awt.event.ActionListener()
    {
        public void actionPerformed(java.awt.event.ActionEvent evt)
        {
            Update_Cust_IDActionPerformed(evt);
        }
    });

    Update_Store_ID_Output.setText("Store ID");
    Update_Store_ID_Output.setPreferredSize(new java.awt.Dimension(150, 50));
    Update_Store_ID_Output.addActionListener(new java.awt.event.ActionListener()
    {
        public void actionPerformed(java.awt.event.ActionEvent evt)
        {
            Update_Store_ID_OutputActionPerformed(evt);
        }
    });

    Update_FName_Output.setText("First Name");

    Update_SName_Output.setText("Last Name");

    Update_Email_Output.setText("Email Address");

    Update_Active_Output.setText("Active");

    Update_Button.setText("Update Client");
    Update_Button.setPreferredSize(new java.awt.Dimension(67, 22));
    Update_Button.addActionListener(new java.awt.event.ActionListener()
    {
        public void actionPerformed(java.awt.event.ActionEvent evt)
        {
            Update_ButtonActionPerformed(evt);
        }
    });

    Update_Back_Button.setText("Back");
    Update_Back_Button.addActionListener(new java.awt.event.ActionListener()
    {
        public void actionPerformed(java.awt.event.ActionEvent evt)
        {
            Update_Back_ButtonActionPerformed(evt);
        }
    });

    Update_Check_Client_Button.setText("Check Client");
    Update_Check_Client_Button.addActionListener(new java.awt.event.ActionListener()
    {
        public void actionPerformed(java.awt.event.ActionEvent evt)
        {
            Update_Check_Client_ButtonActionPerformed(evt);
        }
    });

    jLabel2.setText("Customer Details");

    Address1_Output.setText("Address 1");
    Address1_Output.addActionListener(new java.awt.event.ActionListener()
    {
        public void actionPerformed(java.awt.event.ActionEvent evt)
        {
            Address1_OutputActionPerformed(evt);
        }
    });

    Address2_Output.setText("Address 2");

    jLabel3.setText("Details Being Changed");

    Update_StoreID_Input.setText("Store ID");
    Update_StoreID_Input.addMouseListener(new java.awt.event.MouseAdapter()
    {
        public void mouseClicked(java.awt.event.MouseEvent evt)
        {
            Update_StoreID_InputMouseClicked(evt);
        }
    });
    Update_StoreID_Input.addActionListener(new java.awt.event.ActionListener()
    {
        public void actionPerformed(java.awt.event.ActionEvent evt)
        {
            Update_StoreID_InputActionPerformed(evt);
        }
    });

    Update_FName_Input.setText("First Name");
    Update_FName_Input.addMouseListener(new java.awt.event.MouseAdapter()
    {
        public void mouseClicked(java.awt.event.MouseEvent evt)
        {
            Update_FName_InputMouseClicked(evt);
        }
    });
    Update_FName_Input.addActionListener(new java.awt.event.ActionListener()
    {
        public void actionPerformed(java.awt.event.ActionEvent evt)
        {
            Update_FName_InputActionPerformed(evt);
        }
    });

    Update_LName_Input.setText("Last Name");
    Update_LName_Input.addMouseListener(new java.awt.event.MouseAdapter()
    {
        public void mouseClicked(java.awt.event.MouseEvent evt)
        {
            Update_LName_InputMouseClicked(evt);
        }
    });
    Update_LName_Input.addActionListener(new java.awt.event.ActionListener()
    {
        public void actionPerformed(java.awt.event.ActionEvent evt)
        {
            Update_LName_InputActionPerformed(evt);
        }
    });

    Update_Email_Input.setText("Email Address");
    Update_Email_Input.addMouseListener(new java.awt.event.MouseAdapter()
    {
        public void mouseClicked(java.awt.event.MouseEvent evt)
        {
            Update_Email_InputMouseClicked(evt);
        }
    });
    Update_Email_Input.addActionListener(new java.awt.event.ActionListener()
    {
        public void actionPerformed(java.awt.event.ActionEvent evt)
        {
            Update_Email_InputActionPerformed(evt);
        }
    });

    Update_Active_Input.setText("Active");
    Update_Active_Input.addMouseListener(new java.awt.event.MouseAdapter()
    {
        public void mouseClicked(java.awt.event.MouseEvent evt)
        {
            Update_Active_InputMouseClicked(evt);
        }
    });
    Update_Active_Input.addActionListener(new java.awt.event.ActionListener()
    {
        public void actionPerformed(java.awt.event.ActionEvent evt)
        {
            Update_Active_InputActionPerformed(evt);
        }
    });

    Update_Address1_Input.setText("Address 1");
    Update_Address1_Input.addMouseListener(new java.awt.event.MouseAdapter()
    {
        public void mouseClicked(java.awt.event.MouseEvent evt)
        {
            Update_Address1_InputMouseClicked(evt);
        }
    });
    Update_Address1_Input.addActionListener(new java.awt.event.ActionListener()
    {
        public void actionPerformed(java.awt.event.ActionEvent evt)
        {
            Update_Address1_InputActionPerformed(evt);
        }
    });

    Update_Address2_Input.setText("Address 2");
    Update_Address2_Input.addMouseListener(new java.awt.event.MouseAdapter()
    {
        public void mouseClicked(java.awt.event.MouseEvent evt)
        {
            Update_Address2_InputMouseClicked(evt);
        }
    });
    Update_Address2_Input.addActionListener(new java.awt.event.ActionListener()
    {
        public void actionPerformed(java.awt.event.ActionEvent evt)
        {
            Update_Address2_InputActionPerformed(evt);
        }
    });

    jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
    jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
    jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Update_SName_Output)
                        .addComponent(Update_Email_Output)
                        .addComponent(Address2_Output)
                        .addComponent(Update_Active_Output)
                        .addComponent(Address1_Output)
                        .addComponent(Update_Store_ID_Output, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                        .addComponent(Update_FName_Output)
                        .addComponent(Update_Back_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(42, 42, 42)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(Update_Cust_ID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Update_Address2_Input)
                    .addComponent(Update_Address1_Input)
                    .addComponent(Update_Active_Input)
                    .addComponent(Update_Email_Input, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Update_StoreID_Input)
                    .addComponent(Update_FName_Input)
                    .addComponent(Update_LName_Input)
                    .addComponent(Update_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addComponent(Update_Check_Client_Button, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE))
            .addContainerGap(80, Short.MAX_VALUE))
    );
    jPanel3Layout.setVerticalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(Update_Cust_ID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Update_Check_Client_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(Update_StoreID_Input, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Update_FName_Input)
                            .addGap(7, 7, 7)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Update_SName_Output, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Update_LName_Input, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Update_Email_Input, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                                .addComponent(Update_Email_Output))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Update_Active_Input, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                                .addComponent(Update_Active_Output))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Update_Address1_Input, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                                .addComponent(Address1_Output))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Address2_Output, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                                .addComponent(Update_Address2_Input)))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(Update_Store_ID_Output, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Update_FName_Output, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Update_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Update_Back_Button, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)))
                .addComponent(jSeparator3))
            .addGap(130, 130, 130))
    );

    jTabbedPane1.addTab("Update Clients", jPanel3);

    jPanel4.setBackground(new java.awt.Color(255, 255, 255));
    jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

    Delete_FName.setText("First Name");

    Delete_SName.setText("Last Name");

    Delete_Email.setText("Email Address");

    Delete_Button.setText("Delete Client");
    Delete_Button.addActionListener(new java.awt.event.ActionListener()
    {
        public void actionPerformed(java.awt.event.ActionEvent evt)
        {
            Delete_ButtonActionPerformed(evt);
        }
    });

    Delete_Back_Button.setText("Back");
    Delete_Back_Button.addActionListener(new java.awt.event.ActionListener()
    {
        public void actionPerformed(java.awt.event.ActionEvent evt)
        {
            Delete_Back_ButtonActionPerformed(evt);
        }
    });

    Delete_Cust_ID.setText("Customer ID (Required)");
    Delete_Cust_ID.setPreferredSize(new java.awt.Dimension(150, 50));
    Delete_Cust_ID.addMouseListener(new java.awt.event.MouseAdapter()
    {
        public void mouseClicked(java.awt.event.MouseEvent evt)
        {
            Delete_Cust_IDMouseClicked(evt);
        }
    });
    Delete_Cust_ID.addActionListener(new java.awt.event.ActionListener()
    {
        public void actionPerformed(java.awt.event.ActionEvent evt)
        {
            Delete_Cust_IDActionPerformed(evt);
        }
    });

    Delete_Client_Check_Button.setText("Check to see if client exists");
    Delete_Client_Check_Button.addActionListener(new java.awt.event.ActionListener()
    {
        public void actionPerformed(java.awt.event.ActionEvent evt)
        {
            Delete_Client_Check_ButtonActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel4Layout.createSequentialGroup()
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(96, 96, 96)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Delete_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Delete_SName, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Delete_FName, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Delete_Cust_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(Delete_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Delete_Back_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(206, 206, 206)
                    .addComponent(Delete_Client_Check_Button)))
            .addContainerGap(106, Short.MAX_VALUE))
    );
    jPanel4Layout.setVerticalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel4Layout.createSequentialGroup()
            .addGap(23, 23, 23)
            .addComponent(Delete_Cust_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(Delete_Client_Check_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(26, 26, 26)
            .addComponent(Delete_FName, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(Delete_SName, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(Delete_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(Delete_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(Delete_Back_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(132, Short.MAX_VALUE))
    );

    jTabbedPane1.addTab("Delete Clients", jPanel4);

    javax.swing.GroupLayout Homepage_ContainerLayout = new javax.swing.GroupLayout(Homepage_Container);
    Homepage_Container.setLayout(Homepage_ContainerLayout);
    Homepage_ContainerLayout.setHorizontalGroup(
        Homepage_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(Homepage_ContainerLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(Homepage_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                .addComponent(Home_Page, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Staff_Page, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Reports_Page, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Films_Page, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Notifications_Page, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(17, Short.MAX_VALUE))
    );
    Homepage_ContainerLayout.setVerticalGroup(
        Homepage_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jSeparator1)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Homepage_ContainerLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(Homepage_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(jTabbedPane1)
                .addGroup(Homepage_ContainerLayout.createSequentialGroup()
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(43, 43, 43)
                    .addComponent(Home_Page, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(62, 62, 62)
                    .addComponent(Staff_Page, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(62, 62, 62)
                    .addComponent(Films_Page, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(62, 62, 62)
                    .addComponent(Reports_Page, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(62, 62, 62)
                    .addComponent(Notifications_Page, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(Homepage_Container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(Homepage_Container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ExitActionPerformed
    {//GEN-HEADEREND:event_ExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_ExitActionPerformed

    private void Notifications_PageActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Notifications_PageActionPerformed
    {//GEN-HEADEREND:event_Notifications_PageActionPerformed

    }//GEN-LAST:event_Notifications_PageActionPerformed

    private void Reports_PageActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Reports_PageActionPerformed
    {//GEN-HEADEREND:event_Reports_PageActionPerformed
        Reports form = new Reports();
        form.setSize(800, 650);
        form.setLocationRelativeTo(null);
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Reports_PageActionPerformed

    private void Films_PageActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Films_PageActionPerformed
    {//GEN-HEADEREND:event_Films_PageActionPerformed
        Films form = new Films();
        form.setSize(800, 650);
        form.setLocationRelativeTo(null);
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Films_PageActionPerformed

    private void Staff_PageActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Staff_PageActionPerformed
    {//GEN-HEADEREND:event_Staff_PageActionPerformed
        Staff form = new Staff();
        form.setSize(800, 650);
        form.setLocationRelativeTo(null);
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Staff_PageActionPerformed

    private void Home_PageActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Home_PageActionPerformed
    {//GEN-HEADEREND:event_Home_PageActionPerformed
        HomePage form = new HomePage();
        form.setSize(800, 650);
        form.setLocationRelativeTo(null);
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Home_PageActionPerformed

    private void Delete_Cust_IDActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Delete_Cust_IDActionPerformed
    {//GEN-HEADEREND:event_Delete_Cust_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Delete_Cust_IDActionPerformed

    private void Add_Back_ButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Add_Back_ButtonActionPerformed
    {//GEN-HEADEREND:event_Add_Back_ButtonActionPerformed
        Notifications form = new Notifications();
        form.setSize(800, 650);
        form.setLocationRelativeTo(null);
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Add_Back_ButtonActionPerformed

    private void Delete_Back_ButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Delete_Back_ButtonActionPerformed
    {//GEN-HEADEREND:event_Delete_Back_ButtonActionPerformed
        Notifications form = new Notifications();
        form.setSize(800, 650);
        form.setLocationRelativeTo(null);
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Delete_Back_ButtonActionPerformed

    private void SearchBarKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_SearchBarKeyReleased
    {//GEN-HEADEREND:event_SearchBarKeyReleased
        String searchValue = SearchBar.getText();
        DefaultTableModel tableModel = (DefaultTableModel) Notifications_List_Clients_Table.getModel();
        TableRowSorter<DefaultTableModel> tableRowSorter = new TableRowSorter<>(tableModel);
        Notifications_List_Clients_Table.setRowSorter(tableRowSorter);
        if (searchValue.trim().length() == 0)
        {
            tableRowSorter.setRowFilter(null);
        } else
        {
            tableRowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + searchValue));
        }
    }//GEN-LAST:event_SearchBarKeyReleased

    private void SearchBarMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_SearchBarMouseClicked
    {//GEN-HEADEREND:event_SearchBarMouseClicked
        if (SearchBar.getText().equals("Search..."))
        {
            SearchBar.setText("");
        }
    }//GEN-LAST:event_SearchBarMouseClicked

    private void Add_ButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Add_ButtonActionPerformed
    {//GEN-HEADEREND:event_Add_ButtonActionPerformed
//        String storeID = Add_Store_ID.getText();
        String Name = Add_FName.getText();
        String Surname = ADD_SName.getText();
        String Email = Add_Email.getText();
        String Active = Add_Active.getText();
    }//GEN-LAST:event_Add_ButtonActionPerformed

    private void Delete_Client_Check_ButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Delete_Client_Check_ButtonActionPerformed
    {//GEN-HEADEREND:event_Delete_Client_Check_ButtonActionPerformed
        int ID = Integer.parseInt(Delete_Cust_ID.getText());
        SQLLink.setClientID(ID);
        String SQL = SQLLink.getClient();

        Connection dbConnection = null;
        ResultSet rs = null;
        Statement stmt = null;
        try
        {
            Class.forName(ClassName);
            dbConnection = DriverManager.getConnection(DBURL, Username, Password);
            stmt = dbConnection.createStatement();
            rs = stmt.executeQuery(SQL);
            String output = "";
            String Name = "";
            String Surname = "";
            String Email = "";
            while (rs.next())
            {
                Name = rs.getString("first_name");
                Surname = rs.getString("last_name");
                Email = rs.getString("email");
                output = rs.getString("first_name") + " " + rs.getString("last_name");
                System.out.println("Deleteing: " + output);

            }
            if (output != "")
            {
                Delete_FName.setText(Name);
                Delete_SName.setText(Surname);
                Delete_Email.setText(Email);
                DeleteFlag = true;
            } else
            {
                Delete_FName.setText("No client exists with that client ID, please enter another one");
                Delete_SName.setText("No client exists with that client ID, please enter another one");
                Delete_Email.setText("No client exists with that client ID, please enter another one");
            }
        } catch (ClassNotFoundException ex)
        {
            Logger.getLogger(Prac4.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Class not found, check the JAR");
        } catch (SQLException ex)
        {
            Logger.getLogger(Prac4.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("SQL error: " + ex.getMessage());
        } finally
        {
            try
            {
                if (rs != null)
                {
                    rs.close();
                }
                if (stmt != null)
                {
                    stmt.close();
                }
                if (dbConnection != null)
                {
                    dbConnection.close();
                }
            } catch (SQLException ex)
            {
                Logger.getLogger(Prac4.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println("Error closing database resources: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_Delete_Client_Check_ButtonActionPerformed

    private void Delete_Cust_IDMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_Delete_Cust_IDMouseClicked
    {//GEN-HEADEREND:event_Delete_Cust_IDMouseClicked
        if (Delete_Cust_ID.getText().equals("Customer ID (Required)"))
        {
            Delete_Cust_ID.setText("");
        }
    }//GEN-LAST:event_Delete_Cust_IDMouseClicked

    private void Delete_ButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Delete_ButtonActionPerformed
    {//GEN-HEADEREND:event_Delete_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Delete_ButtonActionPerformed

    private void Address1_OutputActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Address1_OutputActionPerformed
    {//GEN-HEADEREND:event_Address1_OutputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Address1_OutputActionPerformed

    private void Update_Back_ButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Update_Back_ButtonActionPerformed
    {//GEN-HEADEREND:event_Update_Back_ButtonActionPerformed
        Notifications form = new Notifications();
        form.setSize(800, 650);
        form.setLocationRelativeTo(null);
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Update_Back_ButtonActionPerformed

    private void Update_ButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Update_ButtonActionPerformed
    {//GEN-HEADEREND:event_Update_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Update_ButtonActionPerformed

    private void Update_Store_ID_OutputActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Update_Store_ID_OutputActionPerformed
    {//GEN-HEADEREND:event_Update_Store_ID_OutputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Update_Store_ID_OutputActionPerformed

    private void Update_Cust_IDActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Update_Cust_IDActionPerformed
    {//GEN-HEADEREND:event_Update_Cust_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Update_Cust_IDActionPerformed

    private void Update_Check_Client_ButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Update_Check_Client_ButtonActionPerformed
    {//GEN-HEADEREND:event_Update_Check_Client_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Update_Check_Client_ButtonActionPerformed

    private void Update_StoreID_InputActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Update_StoreID_InputActionPerformed
    {//GEN-HEADEREND:event_Update_StoreID_InputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Update_StoreID_InputActionPerformed

    private void Update_FName_InputActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Update_FName_InputActionPerformed
    {//GEN-HEADEREND:event_Update_FName_InputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Update_FName_InputActionPerformed

    private void Update_LName_InputActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Update_LName_InputActionPerformed
    {//GEN-HEADEREND:event_Update_LName_InputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Update_LName_InputActionPerformed

    private void Update_Email_InputActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Update_Email_InputActionPerformed
    {//GEN-HEADEREND:event_Update_Email_InputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Update_Email_InputActionPerformed

    private void Update_Active_InputActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Update_Active_InputActionPerformed
    {//GEN-HEADEREND:event_Update_Active_InputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Update_Active_InputActionPerformed

    private void Update_Address1_InputActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Update_Address1_InputActionPerformed
    {//GEN-HEADEREND:event_Update_Address1_InputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Update_Address1_InputActionPerformed

    private void Update_Address2_InputActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Update_Address2_InputActionPerformed
    {//GEN-HEADEREND:event_Update_Address2_InputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Update_Address2_InputActionPerformed

    private void Update_StoreID_InputMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_Update_StoreID_InputMouseClicked
    {//GEN-HEADEREND:event_Update_StoreID_InputMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Update_StoreID_InputMouseClicked

    private void Update_FName_InputMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_Update_FName_InputMouseClicked
    {//GEN-HEADEREND:event_Update_FName_InputMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Update_FName_InputMouseClicked

    private void Update_LName_InputMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_Update_LName_InputMouseClicked
    {//GEN-HEADEREND:event_Update_LName_InputMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Update_LName_InputMouseClicked

    private void Update_Email_InputMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_Update_Email_InputMouseClicked
    {//GEN-HEADEREND:event_Update_Email_InputMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Update_Email_InputMouseClicked

    private void Update_Active_InputMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_Update_Active_InputMouseClicked
    {//GEN-HEADEREND:event_Update_Active_InputMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Update_Active_InputMouseClicked

    private void Update_Address1_InputMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_Update_Address1_InputMouseClicked
    {//GEN-HEADEREND:event_Update_Address1_InputMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Update_Address1_InputMouseClicked

    private void Update_Address2_InputMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_Update_Address2_InputMouseClicked
    {//GEN-HEADEREND:event_Update_Address2_InputMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Update_Address2_InputMouseClicked

    private void Add_FNameActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Add_FNameActionPerformed
    {//GEN-HEADEREND:event_Add_FNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Add_FNameActionPerformed

    private void ADD_SNameActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ADD_SNameActionPerformed
    {//GEN-HEADEREND:event_ADD_SNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADD_SNameActionPerformed

    private void Add_FNameMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_Add_FNameMouseClicked
    {//GEN-HEADEREND:event_Add_FNameMouseClicked
        if (Add_FName.getText().equals("First Name"))
        {
            Add_FName.setText("");
        }
    }//GEN-LAST:event_Add_FNameMouseClicked

    private void ADD_SNameMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_ADD_SNameMouseClicked
    {//GEN-HEADEREND:event_ADD_SNameMouseClicked
        if (ADD_SName.getText().equals("Last Name"))
        {
            ADD_SName.setText("");
        }
    }//GEN-LAST:event_ADD_SNameMouseClicked

    private void Add_EmailMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_Add_EmailMouseClicked
    {//GEN-HEADEREND:event_Add_EmailMouseClicked
        if (Add_Email.getText().equals("Email Address"))
        {
            Add_Email.setText("");
        }
    }//GEN-LAST:event_Add_EmailMouseClicked

    private void Add_ActiveMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_Add_ActiveMouseClicked
    {//GEN-HEADEREND:event_Add_ActiveMouseClicked
        if (Add_Active.getText().equals("Active"))
        {
            Add_Active.setText("");
        }
    }//GEN-LAST:event_Add_ActiveMouseClicked

    private void Add_Phone_NumberMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_Add_Phone_NumberMouseClicked
    {//GEN-HEADEREND:event_Add_Phone_NumberMouseClicked
        if (Add_Phone_Number.getText().equals("Phone Number"))
        {
            Add_Phone_Number.setText("");
        }
    }//GEN-LAST:event_Add_Phone_NumberMouseClicked

    private void Add_Address1MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_Add_Address1MouseClicked
    {//GEN-HEADEREND:event_Add_Address1MouseClicked
        if (Add_Address1.getText().equals("Address 1"))
        {
            Add_Address1.setText("");
        }
    }//GEN-LAST:event_Add_Address1MouseClicked

    private void Add_Address2MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_Add_Address2MouseClicked
    {//GEN-HEADEREND:event_Add_Address2MouseClicked
        if (Add_Address2.getText().equals("Address 2"))
        {
            Add_Address2.setText("");
        }
    }//GEN-LAST:event_Add_Address2MouseClicked

    private void Add_DistrictMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_Add_DistrictMouseClicked
    {//GEN-HEADEREND:event_Add_DistrictMouseClicked
        if (Add_District.getText().equals("District"))
        {
            Add_District.setText("");
        }
    }//GEN-LAST:event_Add_DistrictMouseClicked

    private void Add_Postal_CodeMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_Add_Postal_CodeMouseClicked
    {//GEN-HEADEREND:event_Add_Postal_CodeMouseClicked
        if (Add_Postal_Code.getText().equals("Postal Code"))
        {
            Add_Postal_Code.setText("");
        }
    }//GEN-LAST:event_Add_Postal_CodeMouseClicked

    private void Update_Cust_IDMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_Update_Cust_IDMouseClicked
    {//GEN-HEADEREND:event_Update_Cust_IDMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Update_Cust_IDMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Notifications.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Notifications.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Notifications.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Notifications.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Notifications().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ADD_SName;
    private javax.swing.JTextField Add_Active;
    private javax.swing.JTextField Add_Address1;
    private javax.swing.JTextField Add_Address2;
    private javax.swing.JButton Add_Back_Button;
    private javax.swing.JButton Add_Button;
    private javax.swing.JComboBox<String> Add_City_Dropbox;
    private javax.swing.JTextField Add_District;
    private javax.swing.JTextField Add_Email;
    private javax.swing.JTextField Add_FName;
    private javax.swing.JTextField Add_Phone_Number;
    private javax.swing.JTextField Add_Postal_Code;
    private javax.swing.JComboBox<String> Add_Store_ID;
    private javax.swing.JTextField Address1_Output;
    private javax.swing.JTextField Address2_Output;
    private javax.swing.JTable ClientsTableInactive;
    private javax.swing.JButton Delete_Back_Button;
    private javax.swing.JButton Delete_Button;
    private javax.swing.JButton Delete_Client_Check_Button;
    private javax.swing.JTextField Delete_Cust_ID;
    private javax.swing.JTextField Delete_Email;
    private javax.swing.JTextField Delete_FName;
    private javax.swing.JTextField Delete_SName;
    private javax.swing.JButton Exit;
    private javax.swing.JButton Films_Page;
    private javax.swing.JButton Home_Page;
    private javax.swing.JPanel Homepage_Container;
    private javax.swing.JTable Notifications_List_Clients_Table;
    private javax.swing.JButton Notifications_Page;
    private javax.swing.JButton Reports_Page;
    private javax.swing.JTextField SearchBar;
    private javax.swing.JTextField SearchBar_Inactive;
    private javax.swing.JButton Staff_Page;
    private javax.swing.JTextField Update_Active_Input;
    private javax.swing.JTextField Update_Active_Output;
    private javax.swing.JTextField Update_Address1_Input;
    private javax.swing.JTextField Update_Address2_Input;
    private javax.swing.JButton Update_Back_Button;
    private javax.swing.JButton Update_Button;
    private javax.swing.JButton Update_Check_Client_Button;
    private javax.swing.JTextField Update_Cust_ID;
    private javax.swing.JTextField Update_Email_Input;
    private javax.swing.JTextField Update_Email_Output;
    private javax.swing.JTextField Update_FName_Input;
    private javax.swing.JTextField Update_FName_Output;
    private javax.swing.JTextField Update_LName_Input;
    private javax.swing.JTextField Update_SName_Output;
    private javax.swing.JTextField Update_StoreID_Input;
    private javax.swing.JTextField Update_Store_ID_Output;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

    Config NotificationsLink = new Config();
    SQLQueries SQLLink = new SQLQueries();
    String DBURL = NotificationsLink.getDBURL();
    String ClassName = NotificationsLink.getClassName();
    String Username = NotificationsLink.getUsername();
    String Password = NotificationsLink.getPassword();

    Boolean DeleteFlag = false;
}
