/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.prac4;

import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author scott
 */
public class Reports extends javax.swing.JFrame
{

    /**
     * Creates new form Reports
     */
    public Reports()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        Homepage_Container = new javax.swing.JPanel();
        Searchbar = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        Reports_Info_Table = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        Home_Page = new javax.swing.JButton();
        Staff_Page = new javax.swing.JButton();
        Films_Page = new javax.swing.JButton();
        Reports_Page = new javax.swing.JButton();
        Notifications_Page = new javax.swing.JButton();
        Exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Homepage_Container.setBackground(new java.awt.Color(255, 255, 255));

        Searchbar.setText("Search...");
        Searchbar.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                SearchbarMouseClicked(evt);
            }
        });
        Searchbar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                SearchbarActionPerformed(evt);
            }
        });
        Searchbar.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                SearchbarKeyReleased(evt);
            }
        });

        Reports_Info_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {1, "Action", 150},
                {2, "Comedy", 200},
                {3, "Drama", 175},
                {4, "Horror", 100}
            },
            new String []
            {
                "Store ID", "Genre", "Number Of Movies"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        Reports_Info_Table.setGridColor(new java.awt.Color(0, 0, 0));
        Reports_Info_Table.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(Reports_Info_Table);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setAlignmentX(0.0F);
        jSeparator1.setAlignmentY(0.0F);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Reports");

        Home_Page.setText("Home");
        Home_Page.setPreferredSize(new java.awt.Dimension(75, 25));
        Home_Page.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                Home_PageActionPerformed(evt);
            }
        });

        Staff_Page.setText("Staff");
        Staff_Page.setPreferredSize(new java.awt.Dimension(75, 25));
        Staff_Page.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                Staff_PageActionPerformed(evt);
            }
        });

        Films_Page.setText("Films");
        Films_Page.setPreferredSize(new java.awt.Dimension(75, 25));
        Films_Page.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                Films_PageActionPerformed(evt);
            }
        });

        Reports_Page.setText("Reports");
        Reports_Page.setPreferredSize(new java.awt.Dimension(75, 25));
        Reports_Page.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                Reports_PageActionPerformed(evt);
            }
        });

        Notifications_Page.setText("Notifications");
        Notifications_Page.setPreferredSize(new java.awt.Dimension(75, 25));
        Notifications_Page.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                Notifications_PageActionPerformed(evt);
            }
        });

        Exit.setText("Exit");
        Exit.setPreferredSize(new java.awt.Dimension(75, 25));
        Exit.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Homepage_ContainerLayout = new javax.swing.GroupLayout(Homepage_Container);
        Homepage_Container.setLayout(Homepage_ContainerLayout);
        Homepage_ContainerLayout.setHorizontalGroup(
            Homepage_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Homepage_ContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Homepage_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(Home_Page, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Staff_Page, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Reports_Page, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Films_Page, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Notifications_Page, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Homepage_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Searchbar)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE))
                .addContainerGap())
        );
        Homepage_ContainerLayout.setVerticalGroup(
            Homepage_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Homepage_ContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Homepage_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Homepage_ContainerLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(Home_Page, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(Staff_Page, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(Films_Page, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(Reports_Page, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(Notifications_Page, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                        .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Homepage_ContainerLayout.createSequentialGroup()
                        .addComponent(Searchbar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jSeparator1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Homepage_Container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Homepage_Container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Home_PageActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Home_PageActionPerformed
    {//GEN-HEADEREND:event_Home_PageActionPerformed
        HomePage form = new HomePage();
        form.setSize(800, 650);
        form.setLocationRelativeTo(null);
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Home_PageActionPerformed

    private void Staff_PageActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Staff_PageActionPerformed
    {//GEN-HEADEREND:event_Staff_PageActionPerformed
        Staff form = new Staff();
        form.setSize(800, 650);
        form.setLocationRelativeTo(null);
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Staff_PageActionPerformed

    private void Films_PageActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Films_PageActionPerformed
    {//GEN-HEADEREND:event_Films_PageActionPerformed
        Films form = new Films();
        form.setSize(800, 650);
        form.setLocationRelativeTo(null);
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Films_PageActionPerformed

    private void Reports_PageActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Reports_PageActionPerformed
    {//GEN-HEADEREND:event_Reports_PageActionPerformed

    }//GEN-LAST:event_Reports_PageActionPerformed

    private void Notifications_PageActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Notifications_PageActionPerformed
    {//GEN-HEADEREND:event_Notifications_PageActionPerformed
        Notifications form = new Notifications();
        form.setSize(800, 650);
        form.setLocationRelativeTo(null);
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Notifications_PageActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ExitActionPerformed
    {//GEN-HEADEREND:event_ExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_ExitActionPerformed

    private void SearchbarKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_SearchbarKeyReleased
    {//GEN-HEADEREND:event_SearchbarKeyReleased
        String searchValue = Searchbar.getText();
        DefaultTableModel tableModel = (DefaultTableModel) Reports_Info_Table.getModel();
        TableRowSorter<DefaultTableModel> tableRowSorter = new TableRowSorter<>(tableModel);
        Reports_Info_Table.setRowSorter(tableRowSorter);
        if (searchValue.trim().length() == 0)
        {
            tableRowSorter.setRowFilter(null);
        } else
        {
            tableRowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + searchValue));
        }
    }//GEN-LAST:event_SearchbarKeyReleased

    private void SearchbarMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_SearchbarMouseClicked
    {//GEN-HEADEREND:event_SearchbarMouseClicked
        if (Searchbar.getText().equals("Search..."))
        {
            Searchbar.setText("");
        }
    }//GEN-LAST:event_SearchbarMouseClicked

    private void SearchbarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_SearchbarActionPerformed
    {//GEN-HEADEREND:event_SearchbarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchbarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Reports().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit;
    private javax.swing.JButton Films_Page;
    private javax.swing.JButton Home_Page;
    private javax.swing.JPanel Homepage_Container;
    private javax.swing.JButton Notifications_Page;
    private javax.swing.JTable Reports_Info_Table;
    private javax.swing.JButton Reports_Page;
    private javax.swing.JTextField Searchbar;
    private javax.swing.JButton Staff_Page;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
